# Generated by Django 4.1 on 2023-12-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_usuario_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="avatar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
