# Generated by Django 4.1 on 2023-12-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_usuario_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("fecha", models.DateField()),
                ("lugar_visitado", models.CharField(max_length=255)),
                ("calificacion_estrellas", models.PositiveIntegerField()),
                ("comentario", models.CharField(max_length=500)),
            ],
        ),
    ]
